# Generated by Django 3.0.6 on 2020-05-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=50)),
                ('no_of_players', models.IntegerField()),
                ('no_of_rounds', models.IntegerField()),
            ],
        ),
    ]
