# Generated by Django 3.0.6 on 2020-05-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='roomname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='host_user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
