# Generated by Django 3.0.6 on 2020-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200516_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='no_of_players',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='no_of_rounds',
            field=models.CharField(max_length=50),
        ),
    ]
