# Generated by Django 3.0.6 on 2020-05-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuser',
            name='roomname',
        ),
        migrations.AddField(
            model_name='guestuser',
            name='room_id',
            field=models.CharField(default='abcdef', max_length=6),
        ),
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='abcdef', max_length=6),
        ),
    ]
