# Generated by Django 3.0.6 on 2020-05-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200523_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='room_id',
            field=models.CharField(default='uvwxyz', max_length=6),
        ),
    ]
